USE [MMB_P53]
GO
/****** Object:  Table [dbo].[AA_codes]    Script Date: 26/10/2020 11:45:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AA_codes](
	[AA_ID] [tinyint] NOT NULL,
	[Amino_Acid] [nvarchar](20) NOT NULL,
	[Three_letter_code] [nvarchar](10) NOT NULL,
	[One_letter_code] [nvarchar](10) NOT NULL,
	[Polarity] [nvarchar](50) NULL,
	[Side_group] [nvarchar](50) NULL,
 CONSTRAINT [PK_AA_codes_AA_ID] PRIMARY KEY CLUSTERED 
(
	[AA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [U_AA_codes_Amino_Acid] UNIQUE NONCLUSTERED 
(
	[Amino_Acid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [U_AA_codes_One_letter_code] UNIQUE NONCLUSTERED 
(
	[One_letter_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY],
 CONSTRAINT [U_AA_codes_Three_letter_code] UNIQUE NONCLUSTERED 
(
	[Three_letter_code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]
GO
