download:
	sudo apt-get install wget
	mkdir -p download
	wget -O ./download/tmp_ensembl2reactome_pe_all_levels.tsv https://reactome.org/download/current/Ensembl2Reactome_PE_All_Levels.txt
	wget -O ./download/tmp_uniprot2reactome_pe_all_levels.tsv https://reactome.org/download/current/UniProt2Reactome_PE_All_Levels.txt
	wget -O ./download/tmp_reactome_pathways.tsv https://reactome.org/download/current/ReactomePathways.txt
	wget -O ./download/tmp_reactome_pathways_relation.tsv https://reactome.org/download/current/ReactomePathwaysRelation.txt

